In [33]:
import numpy as np
cric=np.loadtxt("cric.tsv",skiprows=1)
cric.shape()




TypeError: 'tuple' object is not callable

In [30]:
file=np.loadtxt("cric.tsv",skiprows=1)
file

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [24]:
np.mean(file)

105.75

In [25]:
np.median(file)

72.5

In [34]:
Sachin=cric[:,1]
Sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [35]:
Dravid=cric[:,2]
Dravid

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [36]:
India=cric[:,3]
India

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [37]:
def stats(a):
    median = np.median(a)
    mean = np.mean(a)
    return mean,median

In [38]:
mean1,median1 = stats(Sachin)
print("Mean runs are {} and Median runs are {}".format(mean1,median1))

Mean runs are 63.6 and Median runs are 71.0


In [39]:
mean2,median2 = stats(Dravid)
print("Mean runs are {} and Median runs are {}".format(mean2,median2))

Mean runs are 71.06666666666666 and Median runs are 74.0


In [41]:
mean3,median3 = stats(India)
print("Mean runs are {} and Median runs are {}".format(mean3,median3))

Mean runs are 281.26666666666665 and Median runs are 288.0
